### ISSUE TITLE
Add Twitter authentication

### ISSUE THREAD

**Issue by antonmc** [votesavvyrhok/votesavvy#1]
When a young voter fills out the survey, they can optionally authenticate via Twitter to keep a record of their results, and speed up the survey process. 

This task is to program Twitter authentication when they submit their Twitter name ... it will result in a 'person' entry in the database against which their survey data will be stored.

**Comment by yingqiaojian** [comment]
I am thinking whether the votesavvy web really needs the user authentication function or not. 

There are two kinds of twitter authentication: application-level and user-level. Both of the kinds allow an application to retrieve from twitter the information of a user, for example, the user object and the tweets of the users, The user-level authentication further allows an application to publish tweet through the user's username. 

Since votesavvy is interested in the tweets or the activities of their participants, application-level authentication should be fine. 

However, if votesavvy wants to get the permission from its participants for accessing their tweets, we may call this function as twitter access authorization.

**Comment by yingqiaojian** [comment]
I am implementing the function on retrieving user information with application-level authentication now. If you have some comments, please let me know.

**Comment by antonmc** [comment]
we thought about using it to authenticate to see their information - they can come back and log in to see their answers, suggestions

**Comment by yingqiaojian** [comment]
so, the user-level authentication is used for login with twitter authentication. OK, this is a good point. I will see what I can do now.

**Comment by yingqiaogit** [comment]
The app votesavvyrhok has been transferred successfully to the twitter account @votesavvyrhok now. 

I have updated the votesavvy code with the function of signing in with twitter. There are several problems now. 

Currently, after a user signs in, the first page is returned with the sign in button enabled. Two problems is here. First, the sign in button should be disabled. Second, do we allow a user to sign in at any stage of the survey? In this case, we may need some mechanism to remember where the user is at before the signing in. 

The third problem is related to the users' sessions, do we need to manage the session for a user who has signed in? Or, in a simple way, we record the status of a signed in user in db only. The information of a signed in user includes the credentials of his/her twitter account, and his/her status in the survey. 

Any suggestion?

**Comment by antonmc** [comment]
Nice work, Ying ...

My thoughts ...

1] If the young voter is signed in via Twitter, we'll want to replace the sign in button with the avatar or username of their twitter account to indicate that they're signed in. You should be able to tell if they're signed in from session information - there's probably a well documented way of doing this, if you search - lots of other people do it.

2] We want them to be able to sign in at any point, or not at all - so we need a way of uniquely identifying the young voter when they haven't signed in - for the duration of their session. Maybe a cookie, or local storage attribute that identifies an id for them. If you make a temporary id for them and keep it in local storage, then every time they come back to the page, we can retrieve their data, until they flush that id. 

3] I would say that ideally we would store their data in the database every time they change an answer - although this will might spike our usage of the Cloudant API and cost more ... we'd have to see. It's the most efficient way to synchronize the data, and an obsessive way for us to gather it. An alternative is to save only when they press the save button, or navigate away from/close the the page.

I'm finishing off a form today - just the view component of the form - I'll complete the part that would trigger a save on Thursday afternoon - I have a couple of high priority work tasks to focus on between now and then.

I think each of your three observations is worthy of an issue in itself - maybe you could make those issues? Gerald might be able to comment too.

**Comment by antonmc** [comment]
Note - I also really like the idea that they can come back to the form anytime when they have an account, so if it is only half completed, they can come back and finish it off later.

**Comment by yingqiaogit** [comment]
Thanks for your comments, Anton. 

I will take a look of session management tomorrow. 

Yes, I agree with you that the session management should be separated from this issue. I will close this issue by committing the code, and open several issues.
