### ISSUE TITLE
Set up Vote Savvy account on Bluemix

### ISSUE THREAD

**Issue by antonmc** [votesavvyrhok/votesavvy#11]
Move the runtime to Vote Savvy's account ( away from Anton's )

**Comment by antonmc** [comment]
retained the votes.mybluemix.net route

we need to deploy to a different account now ... I'll add details in Slack

**Comment by antonmc** [comment]
Also - there are new credentials for the database

**Comment by antonmc** [comment]
I invited Ying, Gerald, and Jon to the new Bluemix org

**Comment by yingqiaojian** [comment]
It is a one-month free account, right?
