### ISSUE TITLE
Model data record for young voter information

### ISSUE THREAD

**Issue by antonmc** [votesavvyrhok/votesavvy#5]
We'll need the data from the form, plus their repeated edits of the form, timestamps - we need the data to be recored per person ( as keyed by their Twitter id ) - but also for anonymous users.

**Comment by jaydez** [comment]
I'll draft an example based on the survey they gave us. Then we can discuss it's effectiveness.

**Comment by jaydez** [comment]
Here's a draft of the structure for the JSON document generated by the survey:
It will store the order of the issues, one of three statuses for the sources of political information, and either a yes or no for each activity.

    { 	
	"token": "hash",
	"timestamp": "YYYY-MM-DD'T'HH-MM-SS",
  	"issues":{ 
  		"Justice":0,
  		"Health":1,
  		"Welfare":2,
  		"Immigration":3,
  		"Economy":4,
  		"Environment":5,
  		"Other":6,
  		"Education":7,
  		"Defence":8
  		},
  	"sources":{
  		"Television":0,
  		"Radio":1,
  		"Newspaper":2,
  		"Social":0,
  		"Online":1,
  		"Family":2,
  		"Political":1,
  		"Elected":2
  	},
  	"activity":{
  		"face":0,
  		"message":0,
  		"social":0,
  		"petition":0,
  		"protest":1,
  		"volunteerPolitical":0,
  		"donatePolitical":0,
  		"volunteerCharity":1,
  		"donateCharity":1
  	},
  	"gender":"male/female/other",
  	"birthDate":"YYYY-MM-DD",
  	"work":"fullTime/partTime/student/etc..",
  	"postalCode":"A1A1A1",
  	"twitter":"",
  	"email":"",
  	"other":""}

When the server receives this as a post, it should respond with another json document that includes the data we want to present to the user. We might only need to use the token for logged-in users who must then authenticate their submission.
